import { TPlanList } from '~components/BuyPlanDescription/types';

export const PlanDescriptions: TPlanList = [
  {
    planName: 'Master',
    options: [
      { value: 'App customization' },
      { value: 'App Monetization' },
      // { value: 'Android App Published in the Play Store' },
      // { value: 'Publish your App in the Amazon and the Huawei' },
      { value: 'Review Reminders' },
      { value: 'Push Notifications' },
      { value: 'App Backups' },
      { value: 'Own your code' },
      { value: 'Deep analytics (Firebase)' },
      { value: 'Anti-Spam protection for Google Play' },
      { value: 'AG promotion - 50000 installs' },
      { value: 'Custom Branding' },
      { value: 'No Ads Option' },
      { value: 'Custom Logo on App Launch' },
      { value: 'Premium Support (email, chat, calls)' },
    ],
  },
  {
    planName: 'Individual',
    options: [
      { value: null },
      { value: 'App Monetization' },
      // { value: 'Android App Published in the Play Store' },
      { value: null },
      { value: 'Review Reminders' },
      { value: 'Push Notifications' },
      { value: 'App Backups' },
      { value: 'Own your code' },
      { value: 'Deep analytics (Firebase)' },
      { value: null },
      { value: null },
      { value: 'Custom Branding' },
      { value: 'No Ads Option' },
      { value: 'Custom Logo on App Launch' },
      { value: 'Premium Support (email, chat, calls)' },
    ],
  },
  {
    planName: 'Starter',
    options: [
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: 'App Backups' },
      { value: 'Own your code' },
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: 'No Ads Option' },
      { value: 'Custom Logo on App Launch' },
      { value: 'Premium Support (email, chat, calls)' },
    ],
  },
];

export const PlanDescriptionsMobile: TPlanList = [
  {
    planName: 'Master',
    options: [
      { value: 'No ads' },
      { value: 'App editing' },
      { value: 'Custom logo on App Launch' },
      { value: 'Firebase' },
      { value: 'White label' },
      { value: 'Custom branding' },
      { value: 'Push notifications' },
      { value: 'Control Ads Frequency' },
      { value: 'Rewarded Ads' },
      { value: 'App Backups' },
      { value: 'Premium Support' },
      { value: 'Anti-Spam protection for Google play' },
    ],
  },
  {
    planName: 'Individual',
    options: [
      { value: null },
      { value: 'App editing' },
      { value: 'Custom logo on App Launch' },
      { value: 'Firebase' },
      { value: null },
      { value: null },
      { value: 'Push notifications' },
      { value: 'Control Ads Frequency' },
      { value: 'Rewarded Ads' },
      { value: 'App Backups' },
      { value: 'Premium Support' },
      { value: 'Anti-Spam protection for Google play' },
    ],
  },
  {
    planName: 'Starter',
    options: [
      { value: null },
      { value: 'App editing' },
      { value: 'Custom logo on App Launch' },
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: null },
      { value: 'App Backups' },
      { value: 'Premium Support' },
      { value: 'Anti-Spam protection for Google play' },
    ],
  },
];
